spring:
  application:
    name: workOne

  datasource:
    username: workoneuser
    password: password1!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/workone

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    dir: C:/eclipse/workspace/workOne/uploads